package libs.math.points;

/* 
*  generated by a Python script
*  don't modify it yourself
*/

class DoublePoint
{
	private double x;
	private double y;

	// constructors

	public DoublePoint(double x, double y)
	{
		this.x = x;
		this.y = y;
	}

	public DoublePoint()
	{
		this.x = 0;
		this.y = 0;
	}

	// copy function

	public DoublePoint copy()
	{
		return new DoublePoint(this.x, this.y);
	}

	// test functions

	public boolean isNatural()
	{
		return (this.x > 0) && (this.y > 0);
	}

	// limit functions

	public void xLimit(double min, double max)
	{
		if (x < min) x = min;
		else if (x > max) x = max;
	}
	public void yLimit(double min, double max)
	{
		if (y < min) y = min;
		else if (y > max) y = max;
	}

	public void limit(int xMin, int xMax, int yMin, int yMax)
	{
		xLimit(xMin, xMax);
		yLimit(yMin, yMax);
	}

	public void limit(DoublePoint minPoint, DoublePoint maxPoint)
	{
		xLimit(minPoint.x, maxPoint.x);
		yLimit(minPoint.y, maxPoint.y);
	}

	// add functions

	public void add(double value)
	{
		this.x += value;
		this.y += value;
	}

	public void add(double x, double y)
	{
		this.x += x;
		this.y += y;
	}

	public void add(DoublePoint other)
	{
		this.x += other.x;
		this.y += other.y;
	}

	// sub functions

	public void sub(double value)
	{
		this.x -= value;
		this.y -= value;
	}

	public void sub(double x, double y)
	{
		this.x -= x;
		this.y -= y;
	}

	public void sub(DoublePoint other)
	{
		this.x -= other.x;
		this.y -= other.y;
	}

	// div functions

	public void div(double value)
	{
		this.x /= value;
		this.y /= value;
	}

	public void div(double x, double y)
	{
		this.x /= x;
		this.y /= y;
	}

	public void div(DoublePoint other)
	{
		this.x /= other.x;
		this.y /= other.y;
	}

	// mul functions

	public void mul(double value)
	{
		this.x *= value;
		this.y *= value;
	}

	public void mul(double x, double y)
	{
		this.x *= x;
		this.y *= y;
	}

	public void mul(DoublePoint other)
	{
		this.x *= other.x;
		this.y *= other.y;
	}
}
