package libs.math.points;

/* 
*  generated by a Python script
*  don't modify it yourself
*/

class FloatPoint
{
	private float x;
	private float y;

	// constructors

	public FloatPoint(float x, float y)
	{
		this.x = x;
		this.y = y;
	}

	public FloatPoint()
	{
		this.x = 0;
		this.y = 0;
	}

	// copy function

	public FloatPoint copy()
	{
		return new FloatPoint(this.x, this.y);
	}

	// test functions

	public boolean isNatural()
	{
		return (this.x > 0) && (this.y > 0);
	}

	// limit functions

	public void xLimit(float min, float max)
	{
		if (x < min) x = min;
		else if (x > max) x = max;
	}
	public void yLimit(float min, float max)
	{
		if (y < min) y = min;
		else if (y > max) y = max;
	}

	public void limit(int xMin, int xMax, int yMin, int yMax)
	{
		xLimit(xMin, xMax);
		yLimit(yMin, yMax);
	}

	public void limit(FloatPoint minPoint, FloatPoint maxPoint)
	{
		xLimit(minPoint.x, maxPoint.x);
		yLimit(minPoint.y, maxPoint.y);
	}

	// add functions

	public void add(float value)
	{
		this.x += value;
		this.y += value;
	}

	public void add(float x, float y)
	{
		this.x += x;
		this.y += y;
	}

	public void add(FloatPoint other)
	{
		this.x += other.x;
		this.y += other.y;
	}

	// sub functions

	public void sub(float value)
	{
		this.x -= value;
		this.y -= value;
	}

	public void sub(float x, float y)
	{
		this.x -= x;
		this.y -= y;
	}

	public void sub(FloatPoint other)
	{
		this.x -= other.x;
		this.y -= other.y;
	}

	// div functions

	public void div(float value)
	{
		this.x /= value;
		this.y /= value;
	}

	public void div(float x, float y)
	{
		this.x /= x;
		this.y /= y;
	}

	public void div(FloatPoint other)
	{
		this.x /= other.x;
		this.y /= other.y;
	}

	// mul functions

	public void mul(float value)
	{
		this.x *= value;
		this.y *= value;
	}

	public void mul(float x, float y)
	{
		this.x *= x;
		this.y *= y;
	}

	public void mul(FloatPoint other)
	{
		this.x *= other.x;
		this.y *= other.y;
	}
}
