
package libs.math.points;

/*
*  generated by a Python script
*  don't modify it yourself
*/

class IntPoint
{
	private int x;
	private int y;

	// constructors

	public IntPoint(int x, int y)
	{
		this.x = x;
		this.y = y;
	}

	public IntPoint()
	{
		this.x = 0;
		this.y = 0;
	}

	// copy function

	public IntPoint copy()
	{
		return new IntPoint(this.x, this.y);
	}

	// test functions

	public boolean isNatural()
	{
		return (this.x > 0) && (this.y > 0);
	}

	// limit functions

	public void xLimit(int min, int max)
	{
		if (x < min)
			x = min;
		else if (x > max)
			x = max;
	}

	public void yLimit(int min, int max)
	{
		if (y < min)
			y = min;
		else if (y > max)
			y = max;
	}

	public void limit(int xMin, int xMax, int yMin, int yMax)
	{
		xLimit(xMin, xMax);
		yLimit(yMin, yMax);
	}

	public void limit(IntPoint minPoint, IntPoint maxPoint)
	{
		xLimit(minPoint.x, maxPoint.x);
		yLimit(minPoint.y, maxPoint.y);
	}

	// add functions

	public void add(int value)
	{
		this.x += value;
		this.y += value;
	}

	public void add(int x, int y)
	{
		this.x += x;
		this.y += y;
	}

	public void add(IntPoint other)
	{
		this.x += other.x;
		this.y += other.y;
	}

	// sub functions

	public void sub(int value)
	{
		this.x -= value;
		this.y -= value;
	}

	public void sub(int x, int y)
	{
		this.x -= x;
		this.y -= y;
	}

	public void sub(IntPoint other)
	{
		this.x -= other.x;
		this.y -= other.y;
	}

	// div functions

	public void div(int value)
	{
		this.x /= value;
		this.y /= value;
	}

	public void div(int x, int y)
	{
		this.x /= x;
		this.y /= y;
	}

	public void div(IntPoint other)
	{
		this.x /= other.x;
		this.y /= other.y;
	}

	// mul functions

	public void mul(int value)
	{
		this.x *= value;
		this.y *= value;
	}

	public void mul(int x, int y)
	{
		this.x *= x;
		this.y *= y;
	}

	public void mul(IntPoint other)
	{
		this.x *= other.x;
		this.y *= other.y;
	}
}
