
package machines.machine;

public enum ErrorType
{
	NULL_INSTRUCTION_POINTER,
	NULL_DATA_POINTER,
	
	INVALID_BASE_INSTRUCTION_POINTER, 
	INVALID_INSTRUCTION_POINTER,
	
	INVALID_POINTERS_INDEX, 
	INVALID_BUFFERS_INDEX,
	
	INVALID_DATA_BUFFER_INDEX,
	
	UNKNOWN_INSTRUCTION,
}
