package less.types.tokens;

public enum TokenType
{
	NEWLINE,
	
	MULTI_LINE_COMMENT, COMMENT, NEXT_LINE,
	
	NAME, STRING, NUMBER,
	
	FROM, IMPORT, AS,
	
	GOTO, LABEL,
	IF, THEN, ELSE, END,
	REPEAT, FOR, IN, WHILE, DO,
	SWITCH, CASE, DEFAULT,
	BREAK, CONTINUE,
	
	VAL, VAR, LET, REF,
	DEF, YIELD, RETURN,
	
	TYPE, UNTYPE,
	
	CLASS, SELF, NEW,
	PUBLIC, PRIVATE,
	
	TRUE, FALSE, NULL,
	
	// choose better names:
	
	SEMICOLON, COLON, COMMA, DOT,
	L_PAR, R_PAR, L_BCE, R_BCE, L_BKT, R_BKT,
	
	//
	
	EQ, NE, LT, LE, GT, GE,
	AND, OR, XOR, NOT,
	
	ADD, SUB, DIV, MUL,
	MOD, TDIV, EXP,
	
	BIT_AND, BIT_OR, BIT_XOR, BIT_NOT,
	L_SHIFT, R_SHIFT,
	
	ASSIGN,
	ADD_ASSIGN, SUB_ASSIGN, DIV_ASSIGN, MUL_ASSIGN,
	MOD_ASSIGN, TDIV_ASSIGN, EXP_ASSIGN,
	
	BIT_AND_ASSIGN, BIT_OR_ASSIGN, BIT_XOR_ASSIGN,
	L_SHIFT_ASSIGN, R_SHIFT_ASSIGN,
}
